@host = http://127.0.0.1:8089
@contentType = application/json

### Put task
PUT {{host}}/
content-type: {{contentType}}

{
  "id": "5",
  "input_file": "/media/1tb/Видео/old/4rooms.1995.mkv",
  "output_file": "/media/1tb/Видео/_conversion/1.mp4",
  "ffmpeg_args": {
    "c:v": "libx264"
  }
}